--EXPLOR ALL COUNTRIES OUR COUSTMER CAME FROM
SELECT DISTINCT country FROM gold.dim_customers

--EXPLORE all categories "all major division"
select distinct category, subcategory,product_name from gold.dim_products
order by 1,2,3

--Find the date of first and last order
--how many years of sales area availabe
select
min(order_date)as first_order_date,
max(order_date) as last_order_date,
datediff(year , min(order_date) ,max(order_date) )as order_range_years
from gold.fact_sales

--find the youngest and oldest customer
select 
min(birthdate) as oldest_birtdate,
DATEDIFF(year, min(birthdate) ,getdate()) as oldest_age,
max(birthdate) as youngest_birthdate,
datediff(year, max(birthdate) , getdate()) as youngest_age
from gold.dim_customers

--find how many itemas are sold
select sum(quantity) as total_item_sold from gold.fact_sales

--find the average selling price
select avg(price) as_avg_selling_price from gold.fact_sales

--find the total number of orders
select count(order_number)as total_number_of_order from gold.fact_sales
select count( distinct order_number)as total_number_of_order from gold.fact_sales

--find the total number of product
select count(product_key) as total_product from gold.dim_products
select count(distinct product_key) as total_product from gold.dim_products

--find total number of customer
select count( customer_key) as total_customer from gold.dim_customers

--find the total  numbr of customer that have placed order
select count(distinct customer_key) as total_customer from gold.fact_sales

--GENETARE THE REPORT THAT SHOWN ALL KEY MATRIX OF THE BUISNESS
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value 
FROM gold.fact_sales

UNION ALL

SELECT 'Total Quantity', SUM(quantity) 
FROM gold.fact_sales

UNION ALL

SELECT 'Average Price', AVG(price) 
FROM gold.fact_sales

UNION ALL

SELECT 'Total Nr. Orders', COUNT(DISTINCT order_number) 
FROM gold.fact_sales

UNION ALL

SELECT 'Total Nr. Products', COUNT(product_name) 
FROM gold.dim_products

UNION ALL

SELECT 'Total Nr. Customers', COUNT(customer_key) 
FROM gold.dim_customers;


--find total number of customer by country
select 
country,
count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc

--find total number of customer by gender
select 
gender,
count(customer_key) as total_customers
from gold.dim_customers
group by gender
order by total_customers desc

--find total number of product by category
select 
category,
count(product_key) as total_product
from gold.dim_products
group by category
order by total_product desc

--what is the avg cost in each category
select
category,
avg(cost) as avg_cost
from gold.dim_products
group by category
order by avg_cost desc

--what is the total revenue generated by eachcategory
select
p.category,
sum(f.sales_amount) as total_revenue
from gold.fact_sales as f
left join gold.dim_products as p
on p.product_key=f.product_key
group by category
order by total_revenue desc

--find the total revenue generated by each customer
select

c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales  f
left join gold.dim_customers  c
on c.customer_key=f.customer_key
group by
c.first_name,
c.last_name
order by total_revenue desc

--what is the distribution of item  sold accross the countries
select
sum(f.quantity) as total_qty,
c.country
from gold.fact_sales f
inner join gold.dim_customers c
on c.customer_key=f.customer_key
group  by  c.country
order by total_qty desc


--which five product generate highest revenu
select top 5
p.product_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
inner join gold.dim_products p
on p.product_key=f.product_key
group by p.product_name
order by  total_revenue desc

--which are the top 5 worst performing product
select top 5
p.product_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
inner join gold.dim_products p
on p.product_key=f.product_key
group by p.product_name
order by  total_revenue 





